# docker-compose.yml

version: "3.8"

services:
  organizex:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    entrypoint: ["python", "organizex.py"]
    command: ["--input", "xlsx/file.xlsx", "--output", "xlsx/new_file.xls"]
