version: "3.8"

services:
  organizex:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    environment:
      - PIP_NO_CACHE_DIR=1 # Para garantir que o pip não utilize cache, reduzindo o tamanho da imagem
    entrypoint: ["pipenv", "run", "python", "organizex.py"]
    restart: unless-stopped
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
