services:
  organizex:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: luizinn/organizex:v1.2.0
    volumes:
      - ..:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    entrypoint: ["python", "organizex.py"]
    command: []
